project:
  type: website

website:
  title: "BIOE591: Genomics for Ecology & Conservation"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Assignments"
        href: assignments/index.qmd

format:
  html:
    theme: flatly


